export const INIT_PLE = 'INIT_PLE';

export const SIDE_VISIBLE = 'SIDE_VISIBLE';
export const SIDE_ADD_FILES = 'SIDE_ADD_FILES';
export const SIDE_REMOVE_FILES = 'SIDE_REMOVE_FILES';
export const SIDE_CHANGE_ACTIVE_FILE = 'SIDE_CHANGE_ACTIVE_FILE';
export const SIDE_UPDATE_SELECTED = 'SIDE_UPDATE_SELECTED';
export const SIDE_TOGGLE = 'SIDE_TOGGLE';
export const SIDE_UPDATE_PROGRESS = 'SIDE_UPDATE_PROGRESS';

export const ATTACH_IMAGES = 'ATTACH_IMAGES';
export const ATTACH_IMAGE = 'ATTACH_IMAGE';

export const GRID_ADD_BLOCK = 'GRID_ADD_BLOCK';
export const GRID_REMOVE_BLOCK = 'GRID_REMOVE_BLOCK';
export const GRID_SHUFFLE_BLOCKS = 'GRID_SHUFFLE_BLOCKS';
export const GRID_DUPLICATE_BLOCK = 'GRID_DUPLICATE_BLOCK';
export const GRID_UPDATE_BLOCKS = 'GRID_UPDATE_BLOCKS';
export const GRID_ACTIVE_BLOCK = 'GRID_ACTIVE_BLOCK';
export const GRID_SETTING_UPDATE = 'GRID_SETTING_UPDATE';
export const GRID_CHANGE_COLOR = 'GRID_CHANGE_COLOR';
export const GRID_REMOVE_IMAGES = 'GRID_REMOVE_IMAGES';

export const CROPPER_OPEN = 'CROPPER_OPEN';
export const CROPPER_CLOSE = 'CROPPER_CLOSE';