'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var INIT_PLE = exports.INIT_PLE = 'INIT_PLE';

var SIDE_VISIBLE = exports.SIDE_VISIBLE = 'SIDE_VISIBLE';
var SIDE_ADD_FILES = exports.SIDE_ADD_FILES = 'SIDE_ADD_FILES';
var SIDE_REMOVE_FILES = exports.SIDE_REMOVE_FILES = 'SIDE_REMOVE_FILES';
var SIDE_UPDATE_SELECTED = exports.SIDE_UPDATE_SELECTED = 'SIDE_UPDATE_SELECTED';
var SIDE_TOGGLE = exports.SIDE_TOGGLE = 'SIDE_TOGGLE';
var SIDE_UPDATE_PROGRESS = exports.SIDE_UPDATE_PROGRESS = 'SIDE_UPDATE_PROGRESS';

var GRID_ATTACH_IMAGES = exports.GRID_ATTACH_IMAGES = 'GRID_ATTACH_IMAGES';
var GRID_ATTACH_IMAGE = exports.GRID_ATTACH_IMAGE = 'GRID_ATTACH_IMAGE';

var GRID_ADD_BLOCK = exports.GRID_ADD_BLOCK = 'GRID_ADD_BLOCK';
var GRID_REMOVE_BLOCK = exports.GRID_REMOVE_BLOCK = 'GRID_REMOVE_BLOCK';
var GRID_SHUFFLE_BLOCKS = exports.GRID_SHUFFLE_BLOCKS = 'GRID_SHUFFLE_BLOCKS';
var GRID_DUPLICATE_BLOCK = exports.GRID_DUPLICATE_BLOCK = 'GRID_DUPLICATE_BLOCK';
var GRID_UPDATE_BLOCKS = exports.GRID_UPDATE_BLOCKS = 'GRID_UPDATE_BLOCKS';
var GRID_ACTIVE_BLOCK = exports.GRID_ACTIVE_BLOCK = 'GRID_ACTIVE_BLOCK';
var GRID_SETTING_UPDATE = exports.GRID_SETTING_UPDATE = 'GRID_SETTING_UPDATE';
var GRID_CHANGE_COLOR = exports.GRID_CHANGE_COLOR = 'GRID_CHANGE_COLOR';

var CROPPER_OPEN = exports.CROPPER_OPEN = 'CROPPER_OPEN';
var CROPPER_CLOSE = exports.CROPPER_CLOSE = 'CROPPER_CLOSE';